version: '3'
services:
  frontend:
    build:
      context: ./.docker/frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "yarn dev"
    ports:
      - "3000:3000"
    depends_on:
      - "backend"

  backend:
    build:
      context: ./.docker/backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    command: sh -c "yarn start"
    ports:
      - "8000:8000"