version: '3'
services:
  frontend:
    build:
      context: ./docker/frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "yarn dev"
    ports:
      - "3000:3000"